In [1]:
import pandas as pd
import numpy as np

In [6]:
pd.set_option('display.max_columns', None)

In [12]:
df=pd.read_csv('/media/yahya/data_stuff/DATA/Final Project/ietf-ambiguity-detection/corpus/processed/features/v3/audit/engineered_features.csv')
df_t_labels=pd.read_csv('/media/yahya/data_stuff/DATA/Final Project/ietf-ambiguity-detection/corpus/processed/features/v3/targets/train_labels.csv')

In [7]:
df.describe()

,basic_word_count,basic_character_count,basic_sentence_count,basic_average_word_length,basic_average_sentence_words,basic_average_sentence_characters,vague_term_count,vague_term_density,vague_term_present,vague_quantifier_count,vague_qualifier_count,vague_frequency_count,vague_modal_count,anaphora_count,anaphora_density,anaphora_present,cross_reference_count,cross_reference_density,cross_reference_present,conditional_count,conditional_density,conditional_present,exception_count,exception_density,exception_present,temporal_count,temporal_density,temporal_present,ordering_count,ordering_density,ordering_present,normative_bcp14_count,normative_bcp14_unique_count,normative_bcp14_present,normative_obligation_count,normative_recommendation_count,normative_permission_count,normative_not_recommended_count,normative_should_not_count,normative_shall_not_count,normative_must_not_count,normative_recommended_count,normative_required_count,normative_optional_count,normative_should_count,normative_shall_count,normative_must_count,normative_may_count,syntax_available,syntax_mean_dependency_distance,syntax_max_dependency_depth,syntax_subordinate_clause_count,syntax_coordinate_conjunction_count,context_previous_present,context_previous_word_count,context_previous_character_count,context_previous_sentence_count,context_next_present,context_next_word_count,context_next_character_count,context_next_sentence_count,context_section_depth
count,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.0,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.0,2546.0,2546.0,2546.0,2546.0,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000,2546.000000
mean,24.444226,148.311862,1.000786,5.025775,24.429694,148.221524,0.125687,0.004368,0.113511,0.022388,0.023174,0.006284,0.073841,0.988610,0.038892,0.589945,0.193637,0.007423,0.155145,0.424195,0.015730,0.351925,0.074627,0.002949,0.070699,0.202671,0.008652,0.178319,0.117046,0.004757,0.104478,1.093873,1.045954,0.993716,0.620581,0.251375,0.221917,0.000786,0.038099,0.0,0.156324,0.012569,0.002357,0.001964,0.199921,0.005499,0.456402,0.219953,0.0,0.0,0.0,0.0,0.0,0.959937,21.070699,130.374705,0.969364,0.875491,18.823252,115.410448,0.876277,2.510998
std,11.661610,71.252329,0.028022,0.647686,11.654951,71.216235,0.370726,0.013808,0.317279,0.150603,0.155619,0.079040,0.274751,1.098788,0.041593,0.491940,0.495773,0.020057,0.362114,0.659782,0.024519,0.477664,0.277387,0.011761,0.256372,0.465477,0.020936,0.382856,0.359611,0.016116,0.305939,0.332026,0.240843,0.079040,0.584502,0.451638,0.439511,0.028022,0.191473,0.0,0.369667,0.111425,0.048498,0.044281,0.406837,0.079099,0.564037,0.438262,0.0,0.0,0.0,0.0,0.0,0.196145,12.574138,85.051036,0.272953,0.330226,12.588741,76.539328,0.331708,0.709241
min,4.000000,24.000000,1.000000,3.250000,4.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,17.000000,100.000000,1.000000,4.583333,17.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,13.000000,81.000000,1.000000,1.000000,11.000000,68.000000,1.000000,2.000000
50%,22.000000,135.000000,1.000000,4.954545,22.000000,135.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.035714,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,20.000000,121.000000,1.000000,1.000000,18.000000,112.000000,1.000000,3.000000
75%,30.000000,179.000000,1.000000,5.382003,30.000000,179.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.063244,1.000000,0.000000,0.000000,0.000000,1.000000,0.032258,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.000000,27.000000,165.000000,1.000000,1.000000,26.000000,158.000000,1.000000,3.000000
max,109.000000,630.000000,2.000000,10.600000,109.000000,630.000000,3.000000,0.142857,1.000000,2.000000,2.000000,1.000000,2.000000,7.000000,0.272727,1.000000,4.000000,0.166667,1.000000,6.000000,0.150000,1.000000,2.000000,0.117647,1.000000,4.000000,0.166667,1.000000,3.000000,0.166667,1.000000,4.000000,3.000000,1.000000,4.000000,2.000000,3.000000,1.000000,1.000000,0.0,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,4.000000,3.000000,0.0,0.0,0.0,0.0,0.0,1.000000,154.000000,1296.000000,8.000000,1.000000,119.000000,688.000000,2.000000,5.000000

In [8]:
df.head()

,record_id,family_id,split,basic_word_count,basic_character_count,basic_sentence_count,basic_average_word_length,basic_average_sentence_words,basic_average_sentence_characters,vague_term_count,vague_term_density,vague_term_present,vague_quantifier_count,vague_qualifier_count,vague_frequency_count,vague_modal_count,anaphora_count,anaphora_density,anaphora_present,cross_reference_count,cross_reference_density,cross_reference_present,conditional_count,conditional_density,conditional_present,exception_count,exception_density,exception_present,temporal_count,temporal_density,temporal_present,ordering_count,ordering_density,ordering_present,normative_bcp14_count,normative_bcp14_unique_count,normative_bcp14_present,normative_obligation_count,normative_recommendation_count,normative_permission_count,normative_not_recommended_count,normative_should_not_count,normative_shall_not_count,normative_must_not_count,normative_recommended_count,normative_required_count,normative_optional_count,normative_should_count,normative_shall_count,normative_must_count,normative_may_count,syntax_available,syntax_mean_dependency_distance,syntax_max_dependency_depth,syntax_subordinate_clause_count,syntax_coordinate_conjunction_count,context_previous_present,context_previous_word_count,context_previous_character_count,context_previous_sentence_count,context_next_present,context_next_word_count,context_next_character_count,context_next_sentence_count,context_section_depth
0,8dd0e1eb528a1b0a4ab82a41f9ea8cc3b905d311367f8d...,draft-ietf-6man-rfc2460bis,train,36,241,1,5.527778,36.0,241.0,0,0.0,0,0,0,0,0,2,0.055556,1,0,0.000000,0,2,0.055556,1,0,0.0,0,0,0.0,0,0,0.000000,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0,1,13,84,1,1,15,103,1,1
1,00a36fec91115ee542d1e6e37f77ff5f9b640be722ac80...,draft-ietf-dnsop-svcb-https,test,43,242,1,4.488372,43.0,242.0,0,0.0,0,0,0,0,0,3,0.069767,1,0,0.000000,0,0,0.000000,0,0,0.0,0,0,0.0,0,1,0.023256,1,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0.0,0,0,0,1,5,38,1,0,0,0,0,2
2,02ed4127ca3bd67444c026b44b0e1071ad00768d8808d7...,draft-ietf-dnsop-svcb-https,test,39,254,1,5.358974,39.0,254.0,0,0.0,0,0,0,0,0,0,0.000000,0,1,0.025641,1,0,0.000000,0,0,0.0,0,0,0.0,0,0,0.000000,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0.0,0,0,0,0,0,0,0,1,10,53,1,2
3,0386ae6cc338af22f3fe8ea7fe0edb3b31d78d182f441a...,draft-ietf-dnsop-svcb-https,test,30,173,1,4.533333,30.0,173.0,0,0.0,0,0,0,0,0,1,0.033333,1,0,0.000000,0,1,0.033333,1,0,0.0,0,0,0.0,0,0,0.000000,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0.0,0,0,0,1,37,248,1,1,16,93,1,2
4,056f15a79b01e920cfbaadc3ed1dcbd3ea9413981727df...,draft-ietf-dnsop-svcb-https,test,15,83,1,4.466667,15.0,83.0,0,0.0,0,0,0,0,0,1,0.066667,1,0,0.000000,0,1,0.066667,1,0,0.0,0,0,0.0,0,0,0.000000,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,0,0,0,1,18,106,1,1,17,101,1,2

In [9]:
train_df = df[df['split'] == 'train']

In [14]:
train_df_final = pd.merge(train_df, df_t_labels, on='record_id', how='inner')

In [15]:
train_df_final.head()

,record_id,family_id,split,basic_word_count,basic_character_count,basic_sentence_count,basic_average_word_length,basic_average_sentence_words,basic_average_sentence_characters,vague_term_count,vague_term_density,vague_term_present,vague_quantifier_count,vague_qualifier_count,vague_frequency_count,vague_modal_count,anaphora_count,anaphora_density,anaphora_present,cross_reference_count,cross_reference_density,cross_reference_present,conditional_count,conditional_density,conditional_present,exception_count,exception_density,exception_present,temporal_count,temporal_density,temporal_present,ordering_count,ordering_density,ordering_present,normative_bcp14_count,normative_bcp14_unique_count,normative_bcp14_present,normative_obligation_count,normative_recommendation_count,normative_permission_count,normative_not_recommended_count,normative_should_not_count,normative_shall_not_count,normative_must_not_count,normative_recommended_count,normative_required_count,normative_optional_count,normative_should_count,normative_shall_count,normative_must_count,normative_may_count,syntax_available,syntax_mean_dependency_distance,syntax_max_dependency_depth,syntax_subordinate_clause_count,syntax_coordinate_conjunction_count,context_previous_present,context_previous_word_count,context_previous_character_count,context_previous_sentence_count,context_next_present,context_next_word_count,context_next_character_count,context_next_sentence_count,context_section_depth,label
0,8dd0e1eb528a1b0a4ab82a41f9ea8cc3b905d311367f8d...,draft-ietf-6man-rfc2460bis,train,36,241,1,5.527778,36.0,241.0,0,0.000000,0,0,0,0,0,2,0.055556,1,0,0.0,0,2,0.055556,1,0,0.0,0,0,0.000000,0,0,0.0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0,1,13,84,1,1,15,103,1,1,0
1,16a23128ea688bd9c4d8108f041c8e53580b352a8798cb...,draft-ietf-httpbis-cache-header,train,18,101,1,4.611111,18.0,101.0,0,0.000000,0,0,0,0,0,3,0.166667,1,0,0.0,0,0,0.000000,0,0,0.0,0,0,0.000000,0,0,0.0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0,1,28,173,1,1,30,181,1,1,0
2,3742afcb37bd439ce4ba611bfa04108e82cf6c289fd16e...,draft-ietf-httpbis-cache-header,train,31,190,1,5.064516,31.0,190.0,0,0.000000,0,0,0,0,0,0,0.000000,0,0,0.0,0,1,0.032258,1,0,0.0,0,0,0.000000,0,0,0.0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0.0,0,0,0,1,29,171,1,1,17,94,1,1,0
3,5a3086417e21d1d8a0156667bcab39adca5c9c355eeb87...,draft-ietf-httpbis-cache-header,train,17,109,1,5.352941,17.0,109.0,0,0.000000,0,0,0,0,0,1,0.058824,1,0,0.0,0,0,0.000000,0,0,0.0,0,1,0.058824,1,0,0.0,0,1,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0.0,0,0,0,1,18,100,1,1,5,44,1,1,0
4,954e147ad036ca6ea489509f8754173ef17875a482ae7b...,draft-ietf-httpbis-cache-header,train,22,115,1,4.181818,22.0,115.0,1,0.045455,1,1,0,0,0,3,0.136364,1,0,0.0,0,0,0.000000,0,0,0.0,0,0,0.000000,0,0,0.0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0.0,0,0,0,1,31,172,1,1,6,37,1,2,1